name: test:Deploy to cPanel

on:
  push:
    branches:
      - ci-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Delete old useless files
        uses: appleboy/ssh-action@master
        env: 
          SKIP_FILES: ${{ secrets.SKIP_FILES }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
          TEST: "test env var"
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          envs: SKIP_FILES,TARGET_DIR,TEST
          script: |
            echo $TEST
            echo $TARGET_DIR
            echo $SKIP_FILES
            printf "! -name %s " $(echo $SKIP_FILES)
            cd ${{ env.TARGET_DIR }}
